# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ec54b08db35ec9a726f72bcdc2579347d412a98822d22bcccefb8335d96da1858774f20a5fc655fee4683f8f40df5d3139cec5e298811134ee5c1ddec4ede48d

test:
  secret_key_base: 8f9e23ec16dda955e5e541be50a158127f78cd27029a6b24973f6de96862e5528226f6984ad94dd16caaa209f31361a6633a7541a467271f5dc1ec27473fc686

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
